theme: jekyll-theme-minimal
title: raffaele angius
description: Giornalista. Scrivo di sorveglianza, diritti umani digitali e storie cyber. Sono anche membro del Centro Hermes. In questa pagina raccolgo articoli, inchieste ed eventi ai quali partecipo. 
logo: <img src="faffa/photo_2020-07-26_16-27-25.jpg" alt="hi" class="inline"/>
