theme: jekyll-theme-minimal
logo: /assets/img/profile.png
title: raffaele angius
description: 
Giornalista. Scrivo di sorveglianza, diritti umani digitali e storie cyber. Sono anche membro del Centro Hermes. In questa pagina raccolgo articoli, inchieste ed eventi ai quali partecipo. 

twitter_username: faffa42
github_username:  faffa42

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

