theme: jekyll-theme-minimal
title: raffaele angius
description: Giornalista. Scrivo di sorveglianza, diritti umani digitali e storie cyber. Sono anche membro del Centro Hermes. In questa pagina raccolgo articoli, inchieste ed eventi ai quali partecipo. 
<img src="https://github.com/faffa42/faffa/blob/master/images/profile.png" style="display: block; margin: auto;" />

